const WB_SUPABASE_URL='https://laawaphkfqkshftiyqqy.supabase.co';
const WB_SUPABASE_KEY='sb_publishable_jY73SSA6foPKJoQ2SFYEGQ_bBqMTReB';
const wbHeaders={apikey:WB_SUPABASE_KEY,Authorization:`Bearer ${WB_SUPABASE_KEY}`,'Content-Type':'application/json'};
async function wbGet(path){const r=await fetch(WB_SUPABASE_URL+'/rest/v1/'+path,{headers:wbHeaders});if(!r.ok)throw new Error(await r.text());return r.json()}
async function wbPost(path,body){const r=await fetch(WB_SUPABASE_URL+'/rest/v1/'+path,{method:'POST',headers:{...wbHeaders,Prefer:'return=minimal'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r}
async function wbLoad(){try{const [liveListings,liveReviews]=await Promise.all([wbGet('listings?select=*&status=in.(approved,sold_out)&order=created_at.desc'),wbGet('reviews?select=*&status=eq.approved&order=created_at.desc')]);listings=liveListings.map(i=>({id:i.id,name:i.name,type:i.seller==='WindBank'?'item':'player',price:Number(i.price),stock:Number(i.stock),seller:i.seller,img:i.image_url||'',desc:i.description||'',approved:true}));reviews=liveReviews.map(r=>({id:r.id,name:r.player_name,stars:Number(r.rating),text:r.text,verified:true}));render()}catch(e){console.warn('WindBank Supabase:',e)}}
async function submitListing(){const seller=document.getElementById('seller').value.trim(),name=document.getElementById('listingItem').value.trim(),price=Number(document.getElementById('listingPrice').value),stock=Number(document.getElementById('listingStock').value),image_url=document.getElementById('listingImg').value.trim(),description=document.getElementById('listingDesc').value.trim();if(!seller||!name||price<1||stock<1)return toast('Bitte Name, Item, Preis und Stock ausfüllen.');try{await wbPost('listings',{name,category:'item',price,stock,seller,description,image_url,status:'pending'});toast('✓ Angebot gespeichert – es wartet auf Admin-Freigabe.');['seller','listingItem','listingPrice','listingStock','listingImg','listingDesc'].forEach(id=>document.getElementById(id).value='')}catch(e){console.error(e);toast('Angebot konnte nicht gespeichert werden.')}}
async function submitReview(){const name=document.getElementById('reviewName').value.trim(),rating=Number(document.getElementById('reviewStars').value),text=document.getElementById('reviewText').value.trim();if(!name||!text)return toast('Bitte Name und Erlebnis eintragen.');if(!Number.isInteger(rating)||rating<1||rating>5)return toast('Bitte eine Bewertung von 1 bis 5 Sternen wählen.');try{await wbPost('reviews',{player_name:name,rating,text,status:'pending'});toast('✓ Rezension gespeichert – sie wartet auf Admin-Freigabe.');document.getElementById('reviewName').value='';document.getElementById('reviewText').value=''}catch(e){console.error(e);toast('Rezension konnte nicht gespeichert werden.')}}
function wbAdminRequest(body){return fetch('/api/admin-db',{method:body?'POST':'GET',headers:{...(adminToken?{Authorization:'Bearer '+adminToken}:{}),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Admin-Fehler');return d})}
async function wbRefreshAdmin(){const d=await wbAdminRequest();const old=document.getElementById('wb-admin-live');if(old)old.remove();const host=document.querySelector('#adminContent');if(!host)return;const reviews=d.reviews||[];const box=document.createElement('div');box.id='wb-admin-live';box.style='margin-top:22px;padding-top:18px;border-top:1px solid #282c38';box.innerHTML=`<h3>Live-Shop & Freigaben</h3><p class="section-sub">Diese Daten liegen wirklich in Supabase.</p><div style="display:grid;gap:10px">${d.main.map(x=>`<div class="admin-item"><div><b>${esc(x.name)}</b><div class="meta">${fmt(x.price)} · Stock ${x.stock}</div></div><button class="btn" onclick="wbEditMain('${x.id}',${JSON.stringify(x.name)},${Number(x.price)},${Number(x.stock)},${JSON.stringify(x.image_url||'')})">Bearbeiten</button><button class="btn" onclick="wbAdminDelete('${x.id}')">Löschen</button></div>`).join('')||'<div class="section-sub">Noch keine Hauptangebote.</div>'}</div><button class="btn primary" style="margin-top:12px" onclick="wbNewMain()">+ Shop-Angebot hinzufügen</button><h3 style="margin-top:24px">Neue Spieler-Angebote</h3><div style="display:grid;gap:10px">${d.pending.map(x=>`<div class="admin-item"><div><b>${esc(x.name)}</b><div class="meta">${esc(x.seller)} · ${fmt(x.price)} · Stock ${x.stock}</div></div><button class="btn primary" onclick="wbApprove('${x.id}')">Freigeben</button><button class="btn" onclick="wbReject('${x.id}')">Ablehnen</button></div>`).join('')||'<div class="section-sub">Keine offenen Spieler-Angebote.</div>'}</div><h3 style="margin-top:24px">Rezensionen</h3><div style="display:grid;gap:10px">${reviews.map(x=>`<div class="admin-item"><div><b>${esc(x.player_name)}</b><div class="meta">${'★'.repeat(Number(x.rating))}${'☆'.repeat(5-Number(x.rating))} · ${esc(x.text)}</div></div><span>${x.status==='approved'?'Freigegeben':x.status==='rejected'?'Abgelehnt':'Wartet'}</span><button class="btn ${x.status==='approved'?'':'primary'}" onclick="wbReviewAction('${x.id}','${x.status==='approved'?'reject':'approve'}')">${x.status==='approved'?'Zurücknehmen':'Freigeben'}</button><button class="btn" onclick="wbReviewAction('${x.id}','delete')">Löschen</button></div>`).join('')||'<div class="section-sub">Noch keine Rezensionen.</div>'}</div>`;host.appendChild(box)}
async function wbApprove(id){try{await wbAdminRequest({action:'approve',id});toast('✓ Angebot freigegeben.');await wbLoad();await wbRefreshAdmin()}catch(e){toast(e.message)}}
async function wbReject(id){try{await wbAdminRequest({action:'reject',id});toast('Angebot abgelehnt.');await wbRefreshAdmin()}catch(e){toast(e.message)}}
async function wbAdminDelete(id){if(!confirm('Shop-Angebot wirklich löschen?'))return;try{await wbAdminRequest({action:'delete',id});toast('Angebot gelöscht.');await wbLoad();await wbRefreshAdmin()}catch(e){toast(e.message)}}
async function wbReviewAction(id,action){try{const apiAction=action==='approve'?'reviewApprove':action==='reject'?'reviewReject':'reviewDelete';await wbAdminRequest({action:apiAction,id});toast(action==='approve'?'✓ Rezension freigegeben.':action==='reject'?'Rezension zurückgenommen.':'Rezension gelöscht.');await wbLoad();await wbRefreshAdmin()}catch(e){toast(e.message)}}
async function wbNewMain(){const name=prompt('Item-Name:');if(!name)return;const price=Number(prompt('Preis in $:','250000'));const stock=Number(prompt('Stock:','32'));const image_url=prompt('Bild-URL (optional):','');try{await wbAdminRequest({action:'createMain',name,price,stock,image_url,description:''});toast('✓ Hauptangebot hinzugefügt.');await wbLoad();await wbRefreshAdmin()}catch(e){toast(e.message)}}
async function wbEditMain(id,name,price,stock,image){const n=prompt('Item-Name:',name);if(!n)return;const p=Number(prompt('Preis in $:',price));const s=Number(prompt('Stock:',stock));const im=prompt('Bild-URL:',image||'');try{await wbAdminRequest({action:'updateMain',id,name:n,price:p,stock:s,image_url:im});toast('✓ Shop-Angebot aktualisiert.');await wbLoad();await wbRefreshAdmin()}catch(e){toast(e.message)}}
function wbInstallAdmin(){if(typeof showAdmin!=='function'||window._wbWrapped)return;window._wbWrapped=true;const original=showAdmin;window.showAdmin=async function(){original();setTimeout(()=>wbRefreshAdmin().catch(e=>toast(e.message)),80)}}

/* Basis-Versicherung: eigenständiger Bereich, ohne den bestehenden Shop umzubauen. */
function wbInstallBaseInsurance(){
 if(document.getElementById('wb-base-insurance'))return;
 const nav=document.querySelector('.links');
 if(nav){const a=document.createElement('a');a.href='#basis-versicherung';a.textContent='Basis-Versicherung';nav.appendChild(a)}
 const host=document.querySelector('main')||document.body;
 const section=document.createElement('section');section.id='wb-base-insurance';section.className='section';section.innerHTML=`
 <div class="wrap">
  <div class="section-head"><div><div class="eyebrow">WindBank Schutz</div><h2 id="basis-versicherung">Versicherung von Basen</h2><div class="section-sub">Schütze deine Basis auf dem Wind SMP gegen definierte Schadensfälle.</div></div><span class="pill">Ingame-Service</span></div>
  <div class="loan" style="grid-template-columns:1.15fr .85fr">
   <div class="loan-card">
    <h3>Wähle deinen Basen-Schutz</h3>
    <p>Die Prämie richtet sich nach dem geschätzten Wert deiner Basis. Du kannst die Konditionen vor dem Antrag direkt berechnen.</p>
    <div class="grid" style="grid-template-columns:repeat(3,1fr);margin-top:18px">
      <div class="card"><div class="body"><span class="pill">BASIC</span><div class="title" style="margin-top:10px">Basis-Schutz</div><div class="meta">Für kleinere Basen</div><div class="price">2%</div><div class="meta">des Basiswerts / Woche</div></div></div>
      <div class="card"><div class="body"><span class="pill">PLUS</span><div class="title" style="margin-top:10px">Plus-Schutz</div><div class="meta">Mehr Schutzumfang</div><div class="price">3,5%</div><div class="meta">des Basiswerts / Woche</div></div></div>
      <div class="card"><div class="body"><span class="pill">PREMIUM</span><div class="title" style="margin-top:10px">Premium-Schutz</div><div class="meta">Maximaler Ingame-Schutz</div><div class="price">5%</div><div class="meta">des Basiswerts / Woche</div></div></div>
    </div>
    <p class="listing-note">Wichtig: Diese Versicherung gilt ausschließlich innerhalb des WindBank/Wind-SMP-Systems und ersetzt keine echte Versicherung.</p>
   </div>
   <div class="loan-card">
    <h3>Beitrag berechnen</h3>
    <div class="field"><label>Spielername</label><input id="wbInsOwner" placeholder="z. B. Lennox"></div>
    <div class="field" style="margin-top:10px"><label>Name der Basis</label><input id="wbInsBase" placeholder="z. B. Spawn Base"></div>
    <div class="field" style="margin-top:10px"><label>Geschätzter Basiswert ($)</label><input id="wbInsValue" type="number" min="1" value="100000" oninput="wbCalcInsurance()"></div>
    <div class="field" style="margin-top:10px"><label>Tarif</label><select id="wbInsPlan" onchange="wbCalcInsurance()"><option value="0.02">Basis-Schutz — 2%</option><option value="0.035">Plus-Schutz — 3,5%</option><option value="0.05">Premium-Schutz — 5%</option></select></div>
    <div style="margin-top:18px;padding:15px;border:1px solid var(--line);border-radius:13px;background:#0b0d12"><div class="meta">Wöchentlicher Beitrag</div><div class="rate" id="wbInsPrice">$2.000</div></div>
    <button class="btn primary" style="width:100%;margin-top:12px" onclick="wbSubmitInsurance()">Versicherung anfragen</button>
    <div class="listing-note" id="wbInsStatus">Der Antrag wird zunächst auf diesem Gerät gespeichert.</div>
   </div>
  </div>
 </div>`;
 const reviews=document.querySelector('#reviews');
 if(reviews&&reviews.parentNode)reviews.parentNode.insertBefore(section,reviews);else host.appendChild(section);
}
function wbCalcInsurance(){const value=Math.max(0,Number(document.getElementById('wbInsValue')?.value||0));const rate=Number(document.getElementById('wbInsPlan')?.value||.02);const el=document.getElementById('wbInsPrice');if(el)el.textContent='$'+Math.round(value*rate).toLocaleString('de-DE')}
function wbSubmitInsurance(){const owner=document.getElementById('wbInsOwner')?.value.trim(),base=document.getElementById('wbInsBase')?.value.trim(),value=Math.max(0,Number(document.getElementById('wbInsValue')?.value||0)),plan=document.getElementById('wbInsPlan')?.value;if(!owner||!base||value<1)return toast('Bitte Spielername, Basisname und Basiswert ausfüllen.');const req={id:'ins_'+Date.now(),owner,base,value,rate:Number(plan),createdAt:new Date().toISOString(),status:'pending'};const old=JSON.parse(localStorage.getItem('wb_base_insurance_requests')||'[]');old.push(req);localStorage.setItem('wb_base_insurance_requests',JSON.stringify(old));document.getElementById('wbInsStatus').textContent='✓ Anfrage gespeichert. WindBank kann sie anschließend prüfen.';toast('✓ Versicherungsanfrage gespeichert.');}
document.addEventListener('DOMContentLoaded',()=>{setTimeout(wbLoad,400);setTimeout(wbInstallAdmin,700);setTimeout(wbInstallBaseInsurance,800);setInterval(wbLoad,30000)});
